#!/usr/bin/env python3
"""Generates NulConnect/src/core/Localization.generated.inc.

Sources:
  * the macOS app's Localizable.strings files (shared vocabulary), and
  * NulConnect/res/strings-windows.json, which adds Windows-specific strings
    and overrides macOS wording (e.g. "LaunchDaemon").

Usage: python tools/gen-localization.py [path-to-macOS-NulConnect-source]
"""

import json
import pathlib
import re
import sys

LANGUAGES = ["en", "zh-Hans", "zh-Hant", "ja", "de", "fr", "es"]
ROOT = pathlib.Path(__file__).resolve().parent.parent
MAC_SOURCE = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else pathlib.Path(r"D:\CodeSpace\NulConnect\NulConnect")
OVERLAY = ROOT / "NulConnect" / "res" / "strings-windows.json"
OUTPUT = ROOT / "NulConnect" / "src" / "core" / "Localization.generated.inc"

ENTRY = re.compile(r'^\s*"((?:[^"\\]|\\.)*)"\s*=\s*"((?:[^"\\]|\\.)*)"\s*;\s*$')


def unescape(value: str) -> str:
    return (value.replace('\\"', '"').replace("\\n", "\n").replace("\\t", "\t").replace("\\\\", "\\"))


def load_strings(path: pathlib.Path) -> dict:
    table = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ENTRY.match(line)
        if match:
            table[unescape(match.group(1))] = unescape(match.group(2))
    return table


def cpp_literal(value: str) -> str:
    out = []
    for ch in value:
        code = ord(ch)
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\t":
            out.append("\\t")
        elif 0x20 <= code < 0x7F:
            out.append(ch)
        elif code > 0xFFFF:
            code -= 0x10000
            out.append("\\x%04X\\x%04X" % (0xD800 + (code >> 10), 0xDC00 + (code & 0x3FF)))
        else:
            out.append("\\x%04X" % code)
    # Break the literal after hex escapes so following hex digits are not
    # swallowed into the escape sequence.
    text = "".join(out)
    text = re.sub(r"(\\x[0-9A-F]{4})(?=[0-9A-Fa-f])", r'\1" L"', text)
    return 'L"' + text + '"'


def main() -> None:
    tables = {lang: load_strings(MAC_SOURCE / f"{lang}.lproj" / "Localizable.strings") for lang in LANGUAGES}
    keys = list(tables["en"].keys())
    if OVERLAY.exists():
        overlay = json.loads(OVERLAY.read_text(encoding="utf-8"))
        for key, translations in overlay.items():
            if key.startswith("//"):
                continue
            if key not in keys:
                keys.append(key)
            for lang in LANGUAGES:
                if lang in translations:
                    tables[lang][key] = translations[lang]
    lines = [
        "// Generated by tools/gen-localization.py. Do not edit by hand.",
        "// Columns: " + ", ".join(LANGUAGES),
        "",
    ]
    for key in keys:
        values = [cpp_literal(tables[lang].get(key, tables["en"].get(key, key))) for lang in LANGUAGES]
        lines.append("{" + cpp_literal(key) + ", {" + ", ".join(values) + "}},")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(keys)} entries to {OUTPUT}")


if __name__ == "__main__":
    main()
